[build]
  command = "npx prisma generate && npx prisma db push --accept-data-loss && npm run build"
  publish = ".next"

[functions]
  included_files = ["src/generated/prisma/**", "node_modules/.prisma/**", "node_modules/@prisma/client/**"]
  external_node_modules = ["@prisma/client", ".prisma/client"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
